spring:
  application:
    name: taxi-service-demo
eureka:
  client:
    service-url: #设置服务注册中心的URL
      defaultZone: http://host01:2021/admin/eureka/
server:
  port: 8002
feign:
  hystrix:
    enabled: true

#Admin监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      ##默认是never
#      show-details: ALWAYS
#      enabled: true